#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    bradenton-phpmyadmin-80-http:
      entrypoints:
        - http-8036
      rule: HostRegexp(`^bradenton\.ddev\.site$`)
      
      service: "bradenton-phpmyadmin-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "bradenton-redirectHttps"
    bradenton-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^bradenton\.ddev\.site$`)
      
      service: "bradenton-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "bradenton-redirectHttps"
    bradenton-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^bradenton\.ddev\.site$`)
      
      service: "bradenton-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "bradenton-redirectHttps"
    
    
    bradenton-phpmyadmin-80-https:
      entrypoints:
        - http-8037
      rule: HostRegexp(`^bradenton\.ddev\.site$`)
      
      service: "bradenton-phpmyadmin-80"
      ruleSyntax: v3
      
      tls: true
      
    
    
    bradenton-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^bradenton\.ddev\.site$`)
      
      service: "bradenton-web-80"
      ruleSyntax: v3
      
      tls: true
      
    bradenton-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^bradenton\.ddev\.site$`)
      
      service: "bradenton-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    bradenton-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    bradenton-phpmyadmin-80:
      loadbalancer:
        servers:
          - url: http://ddev-bradenton-phpmyadmin:80
        
    
    bradenton-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-bradenton-web:80
        
    bradenton-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-bradenton-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/bradenton.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/bradenton.key