# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

db:
    type: mariadb:10.2
    disk: 1024

# cacheredis:
#     type: redis-persistent:6.0
#     disk: 1024

# varnish:
#     type: varnish:7.2
#     relationships:
#         application: 'app:http'
#     configuration:
#         vcl: !include
#             type: string
#             path: config.vcl